module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    colors: {
      auburn: '#a52a2a',
      black: '#0c0c0c',
      blue: '#0c0cdb',
      brown: '#622c22',
      darkBlue: '#1111de',
      green: '#4eda12',
      fair: '#ffd6a4',
      grey: '#d8d8d8',
      limeGreen: '#b9da10',
      pink: '#d810ab',
      purple: '#9312db',
      orange: '#db5f0c',
      red: '#d51449',
      silver: '#c0c0c0',
      skin: '#ffcd94',
      skyBlue: '#0cdad0',
      stormtrooperGray: '#748494',
      stormtrooperHeadGray: '#dbdcde',
      stormtrooperHeadShadowGray: '#b5b7b9',
      stormtrooperShadowGray: '#5e6974',
      tan: '#d6b995',
      transparent: 'rgba(0, 0, 0, 0)',
      white: '#fff',
      yellow: '#daab0e',
    },
    fontFamily: {
      sans: ['Poller One', 'cursive'],
      serif: ['Roboto Flex', 'sans-serif'],
    },
    extend: {
      position: {
        inherit: 'inherit',
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
        34: '8rem',
        37: '9.25rem',
        41: '10.25rem',
        46: '11.5rem',
        54: '13.5rem',
        58: '14.5rem',
        62: '15.5rem',
        66: '16.5rem',
        68: '17rem',
        90: '22rem',
        128: '32rem',
        144: '36rem',
      },
      rotate: {
        8: '8deg',
        '-8': '-8deg',
      },
      borderRadius: {
        '4xl': '2rem',
        '50%': '50%',
      },
      border: {
        2: '2px solid',
        3: '3px solid',
      },
      borderB: {
        2: '2px solid',
      },
      left: {
        '1/2': '50%',
      },
      right: {
        '1/2': '50%',
      },
      shadow: {
        xl: '6px 6px 0px 0px #000',
      },
      zIndex: {
        '-1': '-1',
        1: '1',
        2: '2',
        '-2': '-2',
        3: '3',
        '-3': '-3',
        4: '4',
        '-4': '-4',
        5: '5',
        '-5': '-5',
        6: '6',
        '-6': '-6',
        7: '7',
        '-7': '-7',
        8: '8',
        '-8': '-8',
        9: '9',
        '-9': '-9',
      },
    },
  },
  plugins: [],
};
